### ISSUE TITLE
Docker compose?

### ISSUE THREAD

**Issue by rmelendezz** [j6k4m8/goosepaper#85]
Hi, would it be possible to install the docker image using Docker Compose?
I am still a bit new to docker and most of my docker images are managed via Portainer

**Comment by j6k4m8** [comment]
Hi @rmelendezz ! I'm not familiar with portainer, but I imagine something like this should work:


## Option 1: After cloning this repo: 

```
version: '3'
services:
  goosepaper:
    build: .
    volumes:
      # replace with your actual config file
      - ./example-config.json:/app/example-config.json
```

## Option 2: Using a downloaded image (may not be the latest code)

```
version: '3'
services:
  goosepaper:
    image: j6k4m8/goosepaper
    volumes:
      # replace with your actual config file
      - ./example-config.json:/config.json
```

Happy to help you iterate on this with Portainer!
