### ISSUE TITLE
yml-style config?

### ISSUE THREAD

**Issue by j6k4m8** [j6k4m8/goosepaper#9]
my-paper.yml
```yml
stories:
  weather:
  	zipcode: 99999
  twitter:
    accounts:
      - j6m8
      - associatedpress
  rss:
  	feeds:
    	- https://pluralistic.net/feed/
  reddit:
  	subreddits:
    	- news
```

`goosepaper --config my-paper.yml`
